# permissions for end users to view children.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cr-enqueuer
    app.kubernetes.io/managed-by: kustomize
  name: child-viewer-role
rules:
- apiGroups:
  - relation.lambda.coffee
  resources:
  - children
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - relation.lambda.coffee
  resources:
  - children/status
  verbs:
  - get
