# permissions for end users to edit children.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cr-enqueuer
    app.kubernetes.io/managed-by: kustomize
  name: child-editor-role
rules:
- apiGroups:
  - relation.lambda.coffee
  resources:
  - children
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - relation.lambda.coffee
  resources:
  - children/status
  verbs:
  - get
